services:
  mysql:
    image: mysql:8
    container_name: mysql8
    environment:
      MYSQL_ROOT_PASSWORD: cont1234
      MYSQL_DATABASE: creditcard
      MYSQL_USER: admin
      MYSQL_PASSWORD: cont1234
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d


